keys:
  - &trunk00  age1vvwz4n52040ncrl7u74h9nx0hf4mmwec42p3j8pyel2num3meaesgcvqgu
  - &trunk01  age1wndn63aj2k6h0zxmt7zmjxghmy99dag059nvezwtgmqjw48wuu3sz2n6ms
  - &trunk02  age195lv4eae7ps5htcx7gffllatqzjtqa3rahap3ehdpgwf3wx85ctqsl9uyz
  - &leaf00   age153gcfuvuyk5sssp3n4wafnljgqx09ms69rda7h2rferh20fw4ctqp9ukmz
  - &leaf01   age1ae4cr3n7szs09eall2zchuax3t9jyezs8zew9fnerk229ealgs5q52f3r3
  - &leaf02   age18kmyqpehewsa66ms9n0nu4xu6c8upmuq4sa5lyp8mqxcfnlgyp9q86xuet
creation_rules:
  - path_regex: hosts/user/leaf00.yaml
    key_groups:
      - age:
          - *leaf00
  - path_regex: hosts/user/leaf01.yaml
    key_groups:
      - age:
          - *leaf01
  - path_regex: hosts/user/leaf02.yaml
    key_groups:
      - age:
          - *leaf02
  - path_regex: hosts/user/trunk00.yaml
    key_groups:
      - age:
          - *trunk00
  - path_regex: hosts/user/trunk01.yaml
    key_groups:
      - age:
          - *trunk01
  - path_regex: hosts/user/trunk02.yaml
    key_groups:
      - age:
          - *trunk02
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *trunk00
          - *trunk01
          - *trunk02
          - *leaf00
          - *leaf01
          - *leaf02
