keys:
  - &trunk01  age1wndn63aj2k6h0zxmt7zmjxghmy99dag059nvezwtgmqjw48wuu3sz2n6ms
  - &trunk02  age195lv4eae7ps5htcx7gffllatqzjtqa3rahap3ehdpgwf3wx85ctqsl9uyz
creation_rules:
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
          - *trunk01
          - *trunk02
