keys:
  - &allen    71DADA7922B3E08101B3341369C476704F97DBDA
  - &master   age1n0ttzfpf5mpynu26ln7fz2u52gg95tfgqlv5hqykem5jjat8mepqgual97
  - &jump     age13equrg3yhm9rjp6vu5h4tttfe7flk57xc3zxjldn5k6jxanprc9s6ewg5l
  - &dns1     age12ys8lgxx32m8a4qzhh9e0uqzcyheetanny28x9zvfr27khz47f7s0q7a9f
  - &dns2     age1q5urgt9hszq2j9p2qtprl853w6gcy9wapzt73r73xmjla4zhq98scpl8rm
creation_rules:
- path_regex: secrets/dns/[^/]+.$
  key_groups:
  - age:
    - *master
    - *dns1
    - *dns2
- path_regex: secrets/jump/[^/]+.$
  key_groups:
  - age:
    - *master
    - *jump
- path_regex: archive/secrets/[^/]+.$
  key_groups:
  - pgp:
    - *allen
