version: "3"

services:
  pihole:
    container_name: pihole
    hostname: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'America/New_York'
      WEBPASSWORD_FILE: "/run/secrets/pihole"
    volumes:
      - '/mnt/docker/pihole:/etc/pihole'
      - '../pihole/resolv.conf:/etc/resolv.conf:ro'
      - '/run/secrets/pihole:/run/secrets/pihole:ro'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  pihole-sync-receiver:
    image: shirom/pihole-sync:latest
    container_name: pihole-sync-receiver
    volumes:
        - /mnt/docker/piholesync/root:/root
        - /mnt/docker/piholesync/etc-ssh:/etc/ssh
        - /mnt/docker/pihole:/mnt/etc-pihole:ro
        - /run/secrets/sync-pub:/root/.ssh/authorized_keys
    environment:
        - "NODE=receiver"
    ports:
        - 22222:22
